/******************************************************************************* 
 * Copyright (c) 2011 Pablo Hess. All rights reserved.
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 *******************************************************************************/

var CCND1Chromosome11 = "GCTTAACAACAGTAACGTCACACGGACTACAGGGGAGTTTTGTTGAAGTTGCAAAGTCCTGGAGCCTCCAGAGGGCTGTCGGCGCAGTAGCAGCGAGCAGCAGAGTCCGCACGCTCCGGCGAGGGGCAGAAGAGCGCGAGGGAGCGCGGGGCAGCAGAAGCGAGAGCCGAGCGCGGACCCAGCCAGGACCCACAGCCCTCCCCAGCTGCCCAGGAAGAGCCCCAGCCATGGAACACCAGCTCCTGTGCTGCGAAGTGGAAACCATCCGCCGCGCGTACCCCGATGCCAACCTCCTCAACGACCGGGTGCTGCGGGCCATGCTGAAGGCGGAGGAGACCTGCGCGCCCTCGGTGTCCTACTTCAAATGTGTGCAGAAGGAGGTCCTGCCGTCCATGCGGAAGATCGTCGCCACCTGGATGCTGGAG";
var CCND2Chromosome12 = "AGAGCGAGCAGGGGAGAGCGAGACCAGTTTTAAGGGGAGGACCGGTGCGAGTGAGGCAGCCCCGAGGCTCTGCTCGCCCACCACCCAATCCTCGCCTCCCTTCTGCTCCACCTTCTCTCTCTGCCCTCACCTCTCCCCCGAAAACCCCCTATTTAGCCAAAGGAAGGAGGTCAGGGGAACGCTCTCCCCTCCCCTTCCAAAAAACAAAAACAGAAAAACCTTTTTCCAGGCCGGGGAAAGCAGGAGGGAGAGGGGCCGCCGGGCTGGCCATGGAGCTGCTGTGCCACGAGGTGGACCCGGTCCGCAGGGCCGTGCGGGACCGCAACCTGCTCCGAGACGACCGCGTCCTGCAGAACCTGCTCACCATCGAGGAGCGCTACCTTCCGCAGTGCTCCTACTTCAAGTGCGTGCAGAAGGACATCCAACCCTACATGCGCAGAATGGTGGCCACCTGGATGCTGGAG";

var INPUT_DNA = 'searchDna';
var INPUT_DNA_COMP = 'searchDnaComp';
var INPUT_RNA = 'searchRna';
var TEXTAREA_DNA = 'dna_textarea';
var TEXTAREA_RNA = 'rna_textarea';
var TEXTAREA_DNA_COMP = 'dnaComp_textarea';

var SEARCHRESULT_NUMBERS = "columnNumbers";
var SEARCHRESULT_CONTENT = "columnContent";
var SEARCHRESULT_FORM = "dialog-form";

var TIMEOUT_MILLISECONDS = 200;

var BUTTON_SEARCH_DNA = "searchDnaButton";
var BUTTON_SEARCH_DNA_COMP = "searchDnaCompButton";
var BUTTON_SEARCH_RNA = "searchRnaButton";
var BUTTON_CCND1 = "pasteExampleCCND1";
var BUTTON_CCND2 = "pasteExampleCCND2";

var TABS = "tabs";